version: '3'

services:
  postgres:
    image: "postgres:14-alpine"
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: universidade
    ports:
      - "5432:5432"