version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql
    ports:
      - "5432:5432"

  node:
    image: node:latest
    volumes:
      - ./script.js:/app/script.js
    working_dir: /app
    command: ["node", "script.js"]
